"""fixing

Revision ID: a76ea239caa7
Revises: 
Create Date: 2025-01-05 22:16:06.040969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a76ea239caa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_portfolios')
    with op.batch_alter_table('usersportfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_templates', postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.drop_column('usersTemplates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersportfolios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usersTemplates', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
        batch_op.drop_column('users_templates')

    op.create_table('users_portfolios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_portfolios_pkey')
    )
    # ### end Alembic commands ###
